### ISSUE TITLE
Optimize/Modify the README File for the Project

### ISSUE THREAD

**Issue by sagnik20** [sagnik20/QR-Code-Generator#1]
# Aim

- Optimize/Modify the README for the Project.

# Details [The end results I am looking for] :

- An Attractive Header with good Markdown Badges
- Proper Instructions on how new Contributors can contribute. Link this to CONTRIBUTING.md and Code of Conduct
- Instructions on how everyone can use this project

**Comment by konrrad** [comment]
Can I work on this?

**Comment by sagnik20** [comment]
Sure if you want.
