### ISSUE TITLE
Data Store Facility in CSV format

### ISSUE THREAD

**Issue by sagnik20** [sagnik20/QR-Code-Generator#12]
# Aim:

- Add a facility that stores all the data of previously generated QR codes in csv. 

# What I expect from the output:

- Every time a someone generates a QR code its data should be stored in a csv automatically.
- The data should also include a timestamp.

**Comment by sagnik20** [comment]
@deep99doc can you start with this now?

**Comment by deep99doc** [comment]
I'll start working on it tomorrow
