### ISSUE TITLE
Show all contributors in Readme

### ISSUE THREAD

**Issue by sagnik20** [sagnik20/QR-Code-Generator#15]
# Aim

- In the Readme file all contributors name should be made visible.

# What I want exactly?

- All current contributors name should be made visible.
- By name I mean their user name. 
- If you can add their profile pictures to it, then its a added advantage. 
- you can make arrangements as you wish.
- make sure it looks good.

**Comment by sagnik20** [comment]
Its only for participants of Synthax ( https://synthax.live/ ), but if you wish to do this, comment here before it gets assigned to any participants.

**Comment by deep99doc** [comment]
I'll be working on it from the next day
