### ISSUE TITLE
program error when subject contains '/'

### ISSUE THREAD

**Issue by ganiyamustafa** [sagnik20/QR-Code-Generator#28]
The program will error when the subject contains '/' like this

![Screenshot (125)](https://user-images.githubusercontent.com/60203896/95053282-67fb5200-071a-11eb-9a66-ae2271826e8e.png)
![Screenshot (127)](https://user-images.githubusercontent.com/60203896/95053768-1606fc00-071b-11eb-97ca-78a595e39cbf.png)

**Comment by sagnik20** [comment]
Ok.I understand. Can you work on its fix?

**Comment by ganiyamustafa** [comment]
> Ok.I understand. Can you work on its fix?

i think i can, i will try best
