### ISSUE TITLE
Save in User defined file dimensions

### ISSUE THREAD

**Issue by sagnik20** [sagnik20/QR-Code-Generator#4]
# Aim

- Give user an option to define their file dimension

# Details [The end results I am looking for] :

- You can give three option Large , Medium and Small.
- Make sure all these are square in dimension.

**Comment by bpetersonisme** [comment]
I can do that, sure. I was thinking 1024x1024 for large, 512x512 for medium, and 256x256 for small.

**Comment by bpetersonisme** [comment]
It's done, but I had some trouble making the pull request-  seems I don't have the permission for it?
