### ISSUE TITLE
Artistic QR Code generator

### ISSUE THREAD

**Issue by sagnik20** [sagnik20/QR-Code-Generator#7]
# Aim

- Artistic or colourful QR-Codes needs to be generated

# Details [The end results I am looking for] :

- Something like this is expected
![image](https://user-images.githubusercontent.com/36898274/93016736-1232fe80-f5e1-11ea-9867-e28ca75a494c.png)

**Comment by subhayu99** [comment]
@sagnik20 I would like to work on this issue

**Comment by sagnik20** [comment]
@subhayu99 yes you can. go ahead
